### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by devth** [Raynes/irclj#28]
Any docs? :older_man:

**Comment by boxed** [comment]
Yea, like how are you supposed to shut it down? The old 0.4 code checked an atom, but the new code does not. There's a :shutdown? entry in the ref, but that is never read.

**Comment by Raynes** [comment]
@boxed https://github.com/Raynes/irclj/blob/master/src/irclj/core.clj#L160

The lack of documentation is because this rewrite wasn't really totally completed. It's in a working state and is useful, but it's alpha for a reason.

I'll try to find some time to document stuff soon.

**Comment by boxed** [comment]
I think just having two or three examples of the arguments passed to a registered callback and a disconnect function that kills the connection thread would be enough for most usage.

**Comment by boxed** [comment]
I've written a bot based on irclj: https://github.com/boxed/atpshowbot 

I think I'd have had a much easier time if there had just been links to some example project like that when I tried to get started :P

**Comment by Raynes** [comment]
Added some examples to the README as well as a link to your project.

My deepest apologies for not doing it earlier.
